#pragma once

/// \file assigned_numbers.hpp
/// \brief Bluetooth SIG Assigned Numbers lookup tables.
///
/// Build-time generated from the official Bluetooth SIG YAML data at
/// https://bitbucket.org/bluetooth-SIG/public.  The header declares a
/// stable API; the implementation is generated by generate.py.

#include <cstdint>
#include <optional>
#include <string_view>

namespace auracle::assigned_numbers {

/// Look up a Bluetooth SIG company identifier by its 16-bit value.
[[nodiscard]] std::optional<std::string_view> company_name(std::uint16_t id) noexcept;

/// Look up a Bluetooth SIG 16-bit service UUID.
[[nodiscard]] std::optional<std::string_view> service_name(std::uint16_t uuid) noexcept;

/// Look up a Bluetooth SIG 16-bit characteristic UUID.
[[nodiscard]] std::optional<std::string_view> characteristic_name(std::uint16_t uuid) noexcept;

/// Look up a Bluetooth SIG AD Type code.
[[nodiscard]] std::optional<std::string_view> ad_type_name(std::uint8_t type) noexcept;

} // namespace auracle::assigned_numbers
