#pragma once

/// \file assigned_numbers.hpp
/// \brief Bluetooth SIG Assigned Numbers lookup tables.
///
/// Build-time generated from the official Bluetooth SIG YAML data at
/// https://bitbucket.org/bluetooth-SIG/public.  The header declares a
/// stable API; the implementation is generated by generate.py.

#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace auracle::assigned_numbers {

struct service_data_enum_entry_metadata {
    std::uint32_t value;
    std::string short_name;
    std::string description;
    std::vector<std::string> implications;
};

struct service_data_field_metadata {
    std::string field;
    std::string type;
    std::string enum_match;
    std::vector<service_data_enum_entry_metadata> enum_entries;
};

struct service_data_format_metadata {
    std::string service_uuid;
    std::string service_label;
    std::string service_description;
    std::vector<service_data_field_metadata> fields;
    std::uint16_t status_code;
    std::string status_message;
};

struct decoded_field {
    std::string field;
    std::string type;
    std::string value;
};

struct decoded_service_data {
    std::string service_uuid;
    std::string service_label;
    std::vector<std::uint8_t> raw_value;
    std::vector<decoded_field> fields;
    std::uint16_t status_code;
    std::string status_message;
};

/// Look up a Bluetooth SIG company identifier by its 16-bit value.
[[nodiscard]] std::optional<std::string_view> company_name(std::uint16_t id) noexcept;

/// Look up a Bluetooth SIG 16-bit service UUID.
[[nodiscard]] std::optional<std::string_view> service_name(std::uint16_t uuid) noexcept;

/// Look up a Bluetooth SIG service name from a canonical UUID string.
/// Supports both 16-bit values (for example "1852") and SIG base UUIDs
/// (for example "00001852-0000-1000-8000-00805f9b34fb").
[[nodiscard]] std::optional<std::string_view> service_name(std::string_view uuid) noexcept;

/// Look up a Bluetooth SIG 16-bit characteristic UUID.
[[nodiscard]] std::optional<std::string_view> characteristic_name(std::uint16_t uuid) noexcept;

/// Look up a Bluetooth SIG AD Type code.
[[nodiscard]] std::optional<std::string_view> ad_type_name(std::uint8_t type) noexcept;

/// Look up a Bluetooth Generic Audio metadata LTV type code.
[[nodiscard]] std::optional<std::string_view> metadata_type_name(std::uint8_t type) noexcept;

/// Describe a registered service-data packet format without parsing a packet.
/// Returns HTTP-style status codes such as 200 (described) or 404 (unknown format).
[[nodiscard]] service_data_format_metadata describe_service_data_format(
    std::string_view service_uuid);

/// Decode service-data payloads using registered packet definitions.
/// Returns HTTP-style status codes such as 200 (decoded), 404 (no known format),
/// or 422 (malformed payload for the known format).
[[nodiscard]] decoded_service_data decode_service_data(
    std::string_view service_uuid,
    std::span<const std::uint8_t> payload);

} // namespace auracle::assigned_numbers
