#!/usr/bin/env python3
"""Generate C++ lookup tables from Bluetooth SIG assigned numbers YAML.

Reads the official YAML files from the bluetooth-SIG/public repository and
produces a single C++ source file with sorted constexpr arrays and binary-
search lookup functions.

Usage:
    python3 generate.py <input_dir> <output_dir>

Where <input_dir> is the path to the assigned_numbers/ directory inside the
Bluetooth SIG repo and <output_dir> is where assigned_numbers_data.cpp will
be written.

Dependencies: Python 3.10+, PyYAML.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# YAML parsing
# ---------------------------------------------------------------------------


def _clean_name(name: str) -> str:
    """Strip LaTeX artifacts and normalise whitespace."""
    name = re.sub(r"\\textsubscript\{([^}]*)\}", r"\1", name)
    return name.strip()


def _c_escape(s: str) -> str:
    """Escape a string for embedding in a C++ string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _parse_pairs(
    filepath: Path, key_field: str = "value", root_key: str | None = None,
) -> list[tuple[int, str]]:
    """Parse a YAML file with key/name pairs into a sorted (int, str) list.

    Each entry is expected to have *key_field* (a hex string like '0x1800')
    and a 'name' field.  The list under *root_key* is used; if None the
    first top-level list-valued key is used automatically.
    """
    with filepath.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    if root_key is not None:
        items = data[root_key]
    else:
        # Pick the first list-valued key at the top level.
        items = next(v for v in data.values() if isinstance(v, list))

    entries: list[tuple[int, str]] = []
    for item in items:
        raw_key = item.get(key_field)
        raw_name = item.get("name")
        if raw_key is None or raw_name is None:
            continue
        key = int(str(raw_key), 16) if isinstance(raw_key, str) else int(raw_key)
        entries.append((key, _clean_name(str(raw_name))))

    entries.sort(key=lambda e: e[0])
    return entries


def _titleize_words(stem: str) -> str:
    special = {
        "ccid": "CCID",
        "uri": "URI",
    }
    words = []
    for part in stem.split("_"):
        words.append(special.get(part, part.capitalize()))
    return " ".join(words)


def _parse_metadata_ltv_types(directory: Path) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []

    for filepath in sorted(directory.glob("*.yaml")):
        with filepath.open(encoding="utf-8") as fh:
            data = yaml.safe_load(fh)

        items = data.get("supported_ltv_structure", [])
        type_value = None
        for item in items:
            if item.get("parameter") == "Type":
                raw_value = item.get("value")
                if isinstance(raw_value, str) and raw_value.startswith("0x"):
                    type_value = int(raw_value, 16)
                elif isinstance(raw_value, int):
                    type_value = raw_value
                break

        if type_value is None:
            continue

        entries.append((type_value, _titleize_words(filepath.stem)))

    entries.sort(key=lambda e: e[0])
    return entries


# ---------------------------------------------------------------------------
# C++ code generation
# ---------------------------------------------------------------------------

_HEADER = """\
// AUTO-GENERATED by generate.py — do not edit.
// Source: https://bitbucket.org/bluetooth-SIG/public

#include <assigned-numbers/assigned_numbers.hpp>

#include <algorithm>
#include <array>
#include <cstdint>

namespace auracle::assigned_numbers {
namespace {

struct entry16 {
    std::uint16_t key;
    std::string_view name;
};

struct entry8 {
    std::uint8_t key;
    std::string_view name;
};

template <typename Entry, std::size_t N>
[[nodiscard]] std::optional<std::string_view>
lookup(const std::array<Entry, N>& table,
       decltype(Entry::key) key) noexcept {
    auto it = std::lower_bound(
        table.begin(), table.end(), key,
        [](const Entry& e, auto k) { return e.key < k; });
    if (it != table.end() && it->key == key) return it->name;
    return std::nullopt;
}

"""


def _emit_array(
    entries: list[tuple[int, str]],
    name: str,
    entry_type: str,
    hex_width: int,
) -> str:
    """Emit a constexpr std::array definition."""
    lines = [
        f"constexpr std::array<{entry_type}, {len(entries)}> {name} {{{{"
    ]
    for key, value in entries:
        escaped = _c_escape(value)
        lines.append(f'    {{0x{key:0{hex_width}X}, "{escaped}"}},')
    lines.append("}};\n")
    return "\n".join(lines)


def _emit_function(
    func_name: str,
    param_type: str,
    array_name: str,
) -> str:
    """Emit a lookup function definition."""
    return (
        f"std::optional<std::string_view> {func_name}"
        f"({param_type} v) noexcept {{\n"
        f"    return lookup({array_name}, v);\n"
        f"}}\n"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_dir> <output_dir>", file=sys.stderr)
        sys.exit(1)

    input_dir = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])

    # Parse YAML files
    companies = _parse_pairs(
        input_dir / "company_identifiers" / "company_identifiers.yaml",
        root_key="company_identifiers",
    )
    services = _parse_pairs(
        input_dir / "uuids" / "service_uuids.yaml",
        key_field="uuid",
        root_key="uuids",
    )
    characteristics = _parse_pairs(
        input_dir / "uuids" / "characteristic_uuids.yaml",
        key_field="uuid",
        root_key="uuids",
    )
    ad_types = _parse_pairs(
        input_dir / "core" / "ad_types.yaml",
        root_key="ad_types",
    )
    metadata_types = _parse_metadata_ltv_types(
        input_dir / "profiles_and_services" / "generic_audio" / "metadata_ltv"
    )

    # Sanity checks
    if len(companies) < 3000:
        print(
            f"ERROR: Only {len(companies)} company identifiers parsed "
            f"(expected >3000). YAML format may have changed.",
            file=sys.stderr,
        )
        sys.exit(1)
    if len(services) < 50:
        print(
            f"ERROR: Only {len(services)} service UUIDs parsed "
            f"(expected >50). YAML format may have changed.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Generate C++
    parts = [_HEADER]

    parts.append(_emit_array(companies, "kCompanyIds", "entry16", 4))
    parts.append(_emit_array(services, "kServiceUuids", "entry16", 4))
    parts.append(
        _emit_array(characteristics, "kCharacteristicUuids", "entry16", 4)
    )
    parts.append(_emit_array(ad_types, "kAdTypes", "entry8", 2))
    parts.append(_emit_array(metadata_types, "kMetadataTypes", "entry8", 2))

    parts.append("} // anonymous namespace\n")

    parts.append(
        _emit_function("company_name", "std::uint16_t", "kCompanyIds")
    )
    parts.append(
        _emit_function("service_name", "std::uint16_t", "kServiceUuids")
    )
    parts.append(
        _emit_function(
            "characteristic_name", "std::uint16_t", "kCharacteristicUuids"
        )
    )
    parts.append(
        _emit_function("ad_type_name", "std::uint8_t", "kAdTypes")
    )
    parts.append(
        _emit_function("metadata_type_name", "std::uint8_t", "kMetadataTypes")
    )

    parts.append("} // namespace auracle::assigned_numbers\n")

    # Write output
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "assigned_numbers_data.cpp"
    output_file.write_text("\n".join(parts), encoding="utf-8")

    print(
        f"Generated {output_file}: "
        f"{len(companies)} companies, "
        f"{len(services)} services, "
        f"{len(characteristics)} characteristics, "
        f"{len(ad_types)} AD types"
    )


if __name__ == "__main__":
    main()
